# Generated by Django 4.1.7 on 2023-04-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="팀 이름"),
                ),
            ],
            options={"db_table": "team",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(max_length=320, unique=True, verbose_name="이메일"),
                ),
                ("username", models.CharField(max_length=128, verbose_name="사용자 이름")),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.team",
                        verbose_name="소속된 팀",
                    ),
                ),
            ],
            options={"db_table": "user",},
        ),
    ]
